### ISSUE TITLE
What is the license for this example?

### ISSUE THREAD

**Issue by eddiestudies** [paolosalvatori/private-aks-cluster#3]

**Comment by paolosalvatori** [comment]
Hi @eedeleon I should include the license to avoid any misunderstandings. I published the sample also on https://github.com/Azure/azure-quickstart-templates/tree/master/201-private-aks-cluster, and the license is the same, that is the MIT License: https://github.com/Azure/azure-quickstart-templates/blob/master/LICENSE. Please let me know if this answers your question 😃

**Comment by eddiestudies** [comment]
Thanks for the quick reply! This example looks really great
