### ISSUE TITLE
Error using deploy-two-node-pools.sh

### ISSUE THREAD

**Issue by sb1975** [paolosalvatori/private-aks-cluster#4]
Getting the below error after executing the script - "deploy-two-node-pools.sh"
"
Retrieving the user principal name of the current user from the [39b8c8a4-5274-4a19-81e1-75ec6ce2f23e] Azure AD tenant...
[live.com#sudeepbatra@outlook.com] user principal name successfully retrieved from the [39b8c8a4-5274-4a19-81e1-75ec6ce2f23e] Azure AD tenant
Retrieving the objectId of the [live.com#sudeepbatra@outlook.com] user principal name from the [39b8c8a4-5274-4a19-81e1-75ec6ce2f23e] Azure AD tenant...
Failed to retrieve the objectId of the [live.com#sudeepbatra@outlook.com] user principal name
"
and then trying to execute kubectl gives this error.
$ kubectl get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FU4RKYKUF to authenticate.
Unable to connect to the server: dial tcp: lookup private03aks-a8ef06f0.866b9f39-e511-4d4f-9ac0-e386daa0e48b.privatelink.eastus.azmk8s.io on 168.63.129.16:53: no such host

Any help greatly appreciated..

**Comment by paolosalvatori** [comment]
Did you properly replaced placeholders in the [azuredeploy.paramaters.json](https://github.com/paolosalvatori/private-aks-cluster/blob/master/templates/two-node-pools/azuredeploy.parameters.json) file before deploying the cluster?
Are you trying to connect to the private AKS cluster from your laptop or from the jumpbox VM? You can't use kubectl to send commands to the API Server from a machine outside of the VNET hosted by the cluster or from a VNET peered to it.
